#!/bin/true
##############################################################################
#
# This file is part of the "Luna OpenSSL for PQC" project.
#
# The " Luna OpenSSL for PQC " project is provided under the MIT license (see the
# following Web site for further details: https://mit-license.org/ ).
#
# Copyright © 2024 Thales Group
#
##############################################################################
#
# PURPOSE:
#
# .include for makefile 'dbuild.makefile'
# .source file for script 'dbuild-helper.sh'
#

#define (versions):
VER_TCL=8.5.8
VER_TK=8.5.8
VER_SSL=1.0.2o
VER_LIBXML2=2.7.6
VER_LDNS=1.7.0
VER_SQLITE=3.6.22
VER_PYTHON=2.6.4
VER_4SUITE=1.0.2
VER_OPENDNSSEC=2.1.0
VER_RUBY=1.9.1-p376
VER_BIND=9.11.1

#define (where to install):
SFNT_PROJ=dnssec1

#eof
